// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh6kpGkegmhPMvYHWlrVwu6BwUal5BzFw',
    appId: '1:443286525719:web:c891e0d384fba88a3c4952',
    messagingSenderId: '443286525719',
    projectId: 'buckshot-a9242',
    authDomain: 'buckshot-a9242.firebaseapp.com',
    storageBucket: 'buckshot-a9242.firebasestorage.app',
    measurementId: 'G-38SF0REYDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2SxE3dTXQL45N0lcg_9yJxrWrkPU72UI',
    appId: '1:443286525719:android:2e47a17d1ecaf41d3c4952',
    messagingSenderId: '443286525719',
    projectId: 'buckshot-a9242',
    storageBucket: 'buckshot-a9242.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUdDD4UQSuYxYB5QYxC-zMJGW5fy6hksc',
    appId: '1:443286525719:ios:536d9060940619a43c4952',
    messagingSenderId: '443286525719',
    projectId: 'buckshot-a9242',
    storageBucket: 'buckshot-a9242.firebasestorage.app',
    androidClientId: '443286525719-4i92jgs85haqm4aavevl9l649uh3odsc.apps.googleusercontent.com',
    iosClientId: '443286525719-fhl1cniq982cb0k6n37au7dl45nce3q8.apps.googleusercontent.com',
    iosBundleId: 'com.shotgun.buckshot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUdDD4UQSuYxYB5QYxC-zMJGW5fy6hksc',
    appId: '1:443286525719:ios:536d9060940619a43c4952',
    messagingSenderId: '443286525719',
    projectId: 'buckshot-a9242',
    storageBucket: 'buckshot-a9242.firebasestorage.app',
    androidClientId: '443286525719-4i92jgs85haqm4aavevl9l649uh3odsc.apps.googleusercontent.com',
    iosClientId: '443286525719-fhl1cniq982cb0k6n37au7dl45nce3q8.apps.googleusercontent.com',
    iosBundleId: 'com.shotgun.buckshot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDh6kpGkegmhPMvYHWlrVwu6BwUal5BzFw',
    appId: '1:443286525719:web:52cf5cadeafe35943c4952',
    messagingSenderId: '443286525719',
    projectId: 'buckshot-a9242',
    authDomain: 'buckshot-a9242.firebaseapp.com',
    storageBucket: 'buckshot-a9242.firebasestorage.app',
    measurementId: 'G-DCYQEE65V3',
  );

}